### ISSUE TITLE
Adding forms?

### ISSUE THREAD

**Issue by MartijnR** [digidem/simple-odk#6]
It's not clear to me how to add forms. Is there an interface for this?

**Comment by gmaclennan** [comment]
No, there is no interface for this yet. For Github, place the form .xml in a folder `forms` in the root of the github repo, or you can place it in a sub-folder. If there is any media linked in the form xml, it will look for it in the same folder as the form xml file. I keep each form with its associated media in a subfolder under the folder `forms`.

For Gists, just put the form xml as a file in the Gist. It will look for anything with a `.xml` extension.

Nothing is implemented for Firebase yet.

All this needs more documentation, and a user interface, since uploading xml files directly to Github is a little clunky.

**Comment by MartijnR** [comment]
Ok. Thanks. 

Nice work. Not sure if this is useful at all (probably not, because you've implemented the formList API already) but just in case:  this was a similar effort I started last year (and then had no time to continue) https://github.com/enketo/centro
